Repository COSC481W-2021Fall/capstone-thriving-5, pull requests merged in 2021-10, with the labels that each got.

#8 Error Checking for input boxes
  .idea/.gitignore
  help-hero-front-end/app/src/main/java/com/example/helphero/SignUpActivity.java
Labels: enhancement, Sprint 09/29/21

#10 09/29/21 sign up
  backend/HelpHeroServer/HelpHeroServer/__init__.py
  backend/HelpHeroServer/HelpHeroServer/asgi.py
  backend/HelpHeroServer/HelpHeroServer/settings.py
  backend/HelpHeroServer/HelpHeroServer/urls.py
  backend/HelpHeroServer/HelpHeroServer/wsgi.py
  backend/HelpHeroServer/api/__init__.py
  backend/HelpHeroServer/api/admin.py
  backend/HelpHeroServer/api/apps.py
  backend/HelpHeroServer/api/migrations/0001_initial.py
  backend/HelpHeroServer/api/migrations/__init__.py
  backend/HelpHeroServer/api/models.py
  backend/HelpHeroServer/api/serializers.py
  backend/HelpHeroServer/api/tests.py
  backend/HelpHeroServer/api/urls.py
  backend/HelpHeroServer/api/views.py
  backend/HelpHeroServer/manage.py
Labels: enhancement, Sprint 09/29/21

#11 Checks for password requirements
  help-hero-front-end/app/src/main/java/com/example/helphero/SignUpActivity.java
Labels: enhancement, Sprint 09/29/21

#25 impl: Edit check List
  help-hero-front-end/.idea/misc.xml
  help-hero-front-end/app/src/main/java/com/example/helphero/HomeActivity.java
  help-hero-front-end/app/src/main/res/layout/activity_home.xml
  help-hero-front-end/app/src/main/res/layout/activity_sign_in.xml
Labels: enhancement, Sprint 10/20/21, working but could use some polishing

#27 fix: fix bugs in sign in and home page
  help-hero-front-end/app/src/main/java/com/example/helphero/HomeActivity.java
  help-hero-front-end/app/src/main/java/com/example/helphero/SignInActivity.java
  help-hero-front-end/app/src/main/res/layout/activity_home.xml
Labels: Sprint 10/20/21
