Repository COSC481W-2021Fall/capstone-thriving-5, pull requests merged in 2021-11, with the labels that each got.

#33 impl: Edit Contacts Backend
  backend/HelpHeroServer/api/models.py
  backend/HelpHeroServer/api/serializers.py
  backend/HelpHeroServer/api/urls.py
  backend/HelpHeroServer/api/views.py
Labels: Sprint (11/03/21)

#34 impl: Added username display and edit username button
  help-hero-front-end/.idea/misc.xml
  help-hero-front-end/app/src/main/AndroidManifest.xml
  help-hero-front-end/app/src/main/java/com/example/helphero/HomeActivity.java
  help-hero-front-end/app/src/main/res/layout/activity_profile.xml
Labels: enhancement, Sprint (11/03/21)

#37 impl: Added Contact List and Edit and Delete Buttons
  help-hero-front-end/app/build.gradle
  help-hero-front-end/app/src/main/java/com/example/helphero/ProfileActivity.java
  help-hero-front-end/app/src/main/res/layout/activity_profile.xml
Labels: enhancement, Sprint (11/03/21)

#36 Okeefe resources page
  help-hero-front-end/.idea/misc.xml
  help-hero-front-end/app/src/main/AndroidManifest.xml
  help-hero-front-end/app/src/main/java/com/example/helphero/ResourceActivity.java
  help-hero-front-end/app/src/main/res/layout/activity_resource.xml
  help-hero-front-end/app/src/main/res/values/strings.xml
Labels: enhancement, Sprint (11/03/21)

#35 impl: Delete and edit user name functions Backend
  backend/HelpHeroServer/api/models.py
  backend/HelpHeroServer/api/serializers.py
  backend/HelpHeroServer/api/urls.py
  backend/HelpHeroServer/api/views.py
Labels: enhancement, Sprint (11/03/21)

#40 impl: Resource page
  help-hero-front-end/.idea/misc.xml
  help-hero-front-end/app/src/main/AndroidManifest.xml
  help-hero-front-end/app/src/main/java/com/example/helphero/ResourceActivity.java
  help-hero-front-end/app/src/main/res/layout/activity_resource.xml
  help-hero-front-end/app/src/main/res/values/strings.xml
Labels: enhancement, Sprint (11/03/21)

#39 impl: Profile page
  backend/HelpHeroServer/api/models.py
  backend/HelpHeroServer/api/serializers.py
  backend/HelpHeroServer/api/urls.py
  backend/HelpHeroServer/api/views.py
  help-hero-front-end/.idea/misc.xml
  help-hero-front-end/app/build.gradle
  help-hero-front-end/app/src/main/AndroidManifest.xml
  help-hero-front-end/app/src/main/java/com/example/helphero/HomeActivity.java
  help-hero-front-end/app/src/main/java/com/example/helphero/ProfileActivity.java
  help-hero-front-end/app/src/main/res/layout/activity_profile.xml
Labels: enhancement, Sprint (11/03/21)

#41 impl: Display/Change Username and Profile Page fixes
  help-hero-front-end/app/src/main/AndroidManifest.xml
  help-hero-front-end/app/src/main/java/com/example/helphero/ProfileActivity.java
  help-hero-front-end/app/src/main/java/com/example/helphero/SignInActivity.java
  help-hero-front-end/app/src/main/java/com/example/helphero/SignUpActivity.java
  help-hero-front-end/app/src/main/res/layout/activity_profile.xml
Labels: enhancement, Sprint (11/03/21)

#42 impl: Update HomeActivity.java to read through the Daily Affirmations
  help-hero-front-end/.idea/misc.xml
  help-hero-front-end/app/src/main/java/com/example/helphero/HomeActivity.java
  help-hero-front-end/app/src/main/res/layout/activity_home.xml
  help-hero-front-end/app/src/main/res/raw/affirmations.txt
Labels: bug, enhancement, help wanted, Sprint (11/03/21)
