Repository COSC481W-2021Fall/capstone-thriving-5, pull requests merged in 2021-12, with the labels that each got.

#50 impl: Add Contact List and Call Buttons
  help-hero-front-end/app/src/main/AndroidManifest.xml
  help-hero-front-end/app/src/main/java/com/example/helphero/ui/sos/SOSFragment.java
  help-hero-front-end/app/src/main/res/layout/fragment_sos.xml
Labels: enhancement, in progress, sprint 11/22/21

#52 impl: Session Changes
  help-hero-front-end/app/src/main/AndroidManifest.xml
  help-hero-front-end/app/src/main/java/com/example/helphero/MainActivity.java
Labels: polishing, sprint 11/22/21

#61 impl: Sync local with remote task list
  help-hero-front-end/app/src/main/java/com/example/helphero/Database.java
  help-hero-front-end/app/src/main/java/com/example/helphero/ui/home/HomeFragment.java
Labels: sprint 11/22/21
